[build]
  base    = "/"
  command = "yarn build"
  publish = "/public"

# Production context
[context.production]
  command = "yarn build"

# Branch deploy context
[context.branch-deploy]
  command = "yarn build"
